### ISSUE TITLE
Revisions

### ISSUE THREAD

**Issue by hamzaatalif** [mjawad592/my-projects#1]
Buttons doesnt change background color on hover.
The dropdown menu hides when hover on dropdown menu. It only shows when we hover on about us button.
The images box shadow should be done with css.
Contact form colors are not correct.
All buttons should show mouse as pointer when hover on them.
On hover, the boxes should change the x or y position, make them interactive.
Change all footer links to “a” tag.

**Comment by mjawad592** [comment]
noted.
sorting them out.

**Comment by mjawad592** [comment]
all issues are resolved.
